export { default as CodePen } from "./projects/CodePen/CodePen";
export { default as Kagyoaid } from "./projects/Kagyoaid/Kagyoaid";
export { default as Snake } from "./projects/Snake/Snake";
export { default as TamGiang } from "./projects/TamGiang/TamGiang";
export { default as Underdog } from "./projects/Underdog/Underdog";
export { default as Welcome } from "./Welcome/Welcome";
export { default as Flask } from "./projects/Flask/Flask";
export { default as NSDPY } from "./projects/NSDPY/NSDPY";
//export { default as VTAM } from "./projects/VTAM";
